name: lap_tracking
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^5.3.1
  cupertino_icons: ^0.1.2
  device_preview: ^0.4.4
  intl: ^0.16.1
  flutter_tts: ^1.0.0
  google_maps_flutter: ^0.5.27
  flutter_polyline_points: ^0.1.0
  light: ^0.1.1
  animated_text_kit: ^2.0.1
  flutter_launcher_icons: ^0.7.5

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/map_style.txt
